fix(TDQ-19561): avoid open same editor twice
Talend/tdq-studio-se pull request #870
Opened 2021-08-10 03:21 UTC by zshen-talend

2021-08-10 04:00 UTC, xqliu-talend requested changes

2021-08-10 04:10 UTC, zshen-talend commented on main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/CorePlugin.java
> +            return null;
modify it

2021-08-10 04:10 UTC, zshen-talend commented on main/plugins/org.talend.dataprofiler.core/src/org/talend/dataprofiler/core/ui/action/actions/OpenItemEditorAction.java
> +                // don't do any thing if the editor is opening
change it

2021-08-10 04:12 UTC, xqliu-talend submitted a review, later dismissed

2021-08-20 07:16 UTC, xqliu-talend approved these changes

2021-08-20 07:16 UTC, merged